name: build
on: push

jobs:
  vvgo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: make images

      - name: Push images
        shell: bash
        run: |
          for tag in latest $(docker run --rm artifact --release-tags); do
              RELEASE_TAG="$tag" make push
          done
