name: build
on: push

jobs:
  vvgo:
    runs-on: ubuntu-latest
    env:
      VVGO_HOST_IP: ${{ secrets.VVGO_HOST_IP }}
      SSH_ID: ${{secrets.RUNNER_SSH_KEY}

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build images
        shell: bash
        run: |
          RELEASE_TAG=${{ github.sha }} make push
          RELEASE_TAG=$(basename ${{ github.ref }}) make push

      - name: configure ssh
        run: echo "$SSH_ID" > id_rsa && chmod 600 id_rsa
      - name: deploy
        run: ssh -o StrictHostKeyChecking=no -i id_rsa "github_runner@$VVGO_HOST_IP" sudo /home/github_runner/deploy.sh
