name: Fly Deploy
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Disable BuildKit functionality.
        run: |
          sed '/# BEGIN BUILDKIT/,/# END BUILDKIT/d' Dockerfile > fly.Dockerfile

      - uses: superfly/flyctl-actions@1.0
        with:
          args: "deploy --dockerfile fly.Dockerfile"
