name: release

on:
  push:
    branches:
      - master

jobs:
  vvgo:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=latest

          # Install flyctl and deploy
          curl https://get.fly.io/flyctl.sh | sh
          flyctl --app vvgo deploy -i $IMAGE_ID:$VERSION
